D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\ApplicationInsights.config
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Blockchain.WebApplication.dll.config
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Blockchain.WebApplication.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Blockchain.WebApplication.pdb
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Antlr3.Runtime.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\AspNet.ScriptManager.bootstrap.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\AspNet.ScriptManager.jQuery.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.Agent.Intercept.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.DependencyCollector.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.PerfCounterCollector.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.ServerTelemetryChannel.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.Web.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.WindowsServer.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.ApplicationInsights.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AspNet.FriendlyUrls.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AspNet.Web.Optimization.WebForms.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.ScriptManager.MSAjax.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.ScriptManager.WebForms.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.Web.Infrastructure.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Newtonsoft.Json.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\System.Web.Optimization.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\WebGrease.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\System.Web.Optimization.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Antlr3.Runtime.pdb
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AspNet.FriendlyUrls.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Newtonsoft.Json.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.ApplicationInsights.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.DependencyCollector.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.ServerTelemetryChannel.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.WindowsServer.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.Web.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\ru\System.Web.Optimization.resources.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\ru\Microsoft.AspNet.FriendlyUrls.resources.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\obj\Debug\Blockchain.WebApplication.csprojResolveAssemblyReference.cache
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\obj\Debug\Blockchain.WebApplication.csproj.CoreCompileInputs.cache
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\obj\Debug\Blockchain.WebApplication.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\obj\Debug\Blockchain.WebApplication.pdb
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\SmartShares.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\MessagePack.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\System.Threading.Tasks.Extensions.dll
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\SmartShares.pdb
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\MessagePack.xml
D:\Repositories\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\System.Threading.Tasks.Extensions.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\ApplicationInsights.config
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Blockchain.WebApplication.dll.config
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Blockchain.WebApplication.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Blockchain.WebApplication.pdb
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Antlr3.Runtime.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\AspNet.ScriptManager.bootstrap.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\AspNet.ScriptManager.jQuery.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\MessagePack.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.Agent.Intercept.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.DependencyCollector.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.PerfCounterCollector.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.ServerTelemetryChannel.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.Web.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.WindowsServer.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.ApplicationInsights.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AspNet.FriendlyUrls.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AspNet.Web.Optimization.WebForms.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.ScriptManager.MSAjax.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.ScriptManager.WebForms.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.Web.Infrastructure.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Newtonsoft.Json.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\SmartShares.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\System.Threading.Tasks.Extensions.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\System.Web.Optimization.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\WebGrease.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\SmartShares.pdb
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\MessagePack.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Newtonsoft.Json.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\System.Threading.Tasks.Extensions.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\System.Web.Optimization.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Antlr3.Runtime.pdb
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AspNet.FriendlyUrls.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.ApplicationInsights.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.DependencyCollector.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.ServerTelemetryChannel.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.WindowsServer.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\Microsoft.AI.Web.xml
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\ru\System.Web.Optimization.resources.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\bin\ru\Microsoft.AspNet.FriendlyUrls.resources.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\obj\Debug\Blockchain.WebApplication.csprojResolveAssemblyReference.cache
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\obj\Debug\Blockchain.WebApplication.csproj.CoreCompileInputs.cache
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\obj\Debug\Blockchain.WebApplication.dll
E:\GitHub\Blockchain.SmartShares.Simple\Blockchain.WebApplication\obj\Debug\Blockchain.WebApplication.pdb
